### PR TITLE
Change error message 'bust' to 'bus' in func diskCreatedByTemplate

### PR DESCRIPTION
**Pull request by patsevanton**

### CODE REVIEW

**Comment by patsevanton** [comment]
try again

**Review by Didainius — APPROVED** [review]
Thanks

**Comment by patsevanton** [comment]
```
==> Run test short
panic: unable to initialize VCD connection :something went wrong while retrieving URL: parse "": empty url

goroutine 1 [running]:
github.com/vmware/terraform-provider-vcd/v3/vcd.createTemporaryVCDConnection(0x19d7b0b)
	/home/runner/work/terraform-provider-vcd/terraform-provider-vcd/vcd/provider_test.go:76 +0x2e5
github.com/vmware/terraform-provider-vcd/v3/vcd.setCatalogStorageProfile()
	/home/runner/work/terraform-provider-vcd/terraform-provider-vcd/vcd/config_test.go:703 +0x4a
github.com/vmware/terraform-provider-vcd/v3/vcd.TestMain(0xc000500200)
	/home/runner/work/terraform-provider-vcd/terraform-provider-vcd/vcd/config_test.go:682 +0x1cb
main.main()
	_testmain.go:285 +0x272
exit status 2
FAIL	github.com/vmware/terraform-provider-vcd/v3/vcd	0.060s
execution error
make: *** [GNUmakefile:74: test] Error 1
Error: Process completed with exit code 2.
```

**Comment by Didainius** [comment]
> ```
> ==> Run test short
> panic: unable to initialize VCD connection :something went wrong while retrieving URL: parse "": empty url
> 
> goroutine 1 [running]:
> github.com/vmware/terraform-provider-vcd/v3/vcd.createTemporaryVCDConnection(0x19d7b0b)
> 	/home/runner/work/terraform-provider-vcd/terraform-provider-vcd/vcd/provider_test.go:76 +0x2e5
> github.com/vmware/terraform-provider-vcd/v3/vcd.setCatalogStorageProfile()
> 	/home/runner/work/terraform-provider-vcd/terraform-provider-vcd/vcd/config_test.go:703 +0x4a
> github.com/vmware/terraform-provider-vcd/v3/vcd.TestMain(0xc000500200)
> 	/home/runner/work/terraform-provider-vcd/terraform-provider-vcd/vcd/config_test.go:682 +0x1cb
> main.main()
> 	_testmain.go:285 +0x272
> exit status 2
> FAIL	github.com/vmware/terraform-provider-vcd/v3/vcd	0.060s
> execution error
> make: *** [GNUmakefile:74: test] Error 1
> Error: Process completed with exit code 2.
> ```

You can ignore this for the moment.. PR #628 will fix it once merged.

**Review by lvirbalas — APPROVED** [review]
Thanks for noticing!

**Review by dataclouder — APPROVED** [review]

**Pull request merged**
