### PR TITLE
Upgrade Terraform plugin SDK

### PR DESCRIPTION
**Pull request by vbauzysvmware**
* library update
* fixing issues like this (`* Check 10/23 error: vcd_nsxv_firewall_rule.vms: list or set attribute 'source.0.org_networks' must be checked by element count key (source.0.org_networks.#) or element value keys (e.g. source.0.org_networks.0). Set element value checks should use TestCheckTypeSet functions instead.`) in tests.

Tested with VCD 10.3.2

### CODE REVIEW

**Review by Didainius — APPROVED** [review]
Thanks - I am good with PR as long as tests passed here.

**Review by lvirbalas — APPROVED** [review]
Thanks!

**Review by mikeletux — APPROVED** [review]
LGTM!

**Review by adambarreiro — APPROVED** [review]
LGTM!

**Pull request merged**
