### PR TITLE
Fix issue 658 - incomplete retrieval of edge gateways

### PR DESCRIPTION
**Pull request by dataclouder**
When more than 25 edge gateways are present, we get
an "Entity not found" error for most edge gateway operations (Issue #658)

### CODE REVIEW

**Review by lvirbalas — CHANGES_REQUESTED** [review]
Looks good, but please name the PR **describing** the issue as we usually do.

**Review by Didainius — APPROVED** [review]
Thanks! Even if older function is used somewhere we should be good.

**Comment by dataclouder** [comment]
> Looks good, but please name the PR **describing** the issue as we usually do.

Fixed

**Review by lvirbalas — APPROVED** [review]
LGTM!

**Comment by CmdrSharp** [comment]
@dataclouder Thanks for the quick fix! Do you know if there's any chance we might see a new release covering this any time soon? We're affected by the bug at the moment so I'm just curious :)

**Comment by dataclouder** [comment]
@CmdrSharp 
I don't know about the next release timeline. Perhaps @Didainius  or @lvirbalas  can comment.

You could, however, build your own plugin  by running this command in the master branch:

```
make install
```

**Comment by lvirbalas** [comment]
We just had 3.2.0 released, next one shall be around mid-Summer.

**Pull request merged**
